- name: PG | Create users
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    login_user: postgres
  loop: "{{ postgresql_create_users }}"
