---
# tasks file for app
- name: Install Git
  ansible.builtin.apt:
    name: git
    state: present

- name: Clone django repo
  ansible.builtin.git:
    repo: 'https://github.com/mdn/django-locallibrary-tutorial'
    dest: "~/django/locallibrary"
    force: true

- name: Copy Dockerfile to target
  ansible.builtin.copy:
    src: "./Dockerfile"
    dest: "~/django/locallibrary//Dockerfile"

- name: Build Docker image
  community.general.docker_image:
    build:
      path: "~/django/locallibrary/"
    name: "django"
    source: build

- name: Apply migrations
  community.general.docker_container:
    name: "django_c"
    image: "django"
    command: python manage.py makemigrations
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    detach: false

- name: Apply database migrations
  community.general.docker_container:
    name: "django_c"
    image: "django"
    command: python manage.py migrate
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    detach: false

- name: Collect static files
  community.general.docker_container:
    name: "django_c"
    image: "django"
    command: python manage.py collectstatic --noinput
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    detach: false

- name: Run test suite
  community.general.docker_container:
    name: "django_c"
    image: "django"
    command: python manage.py test
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    detach: false

- name: Create Django superuser
  community.general.docker_container:
    name: "django_c"
    image: "django"

    command: "python manage.py createsuperuser --noinput --username=admin --email=admin@{{ inventory_hostname }}.com"
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    detach: false
  ignore_errors: true
- name: Run Docker container
  community.general.docker_container:
    name: "django_c"
    image: "django"
    state: started
    recreate: true
    published_ports:
      - "8000:8000"
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    command: python manage.py runserver 0.0.0.0:8000
