---
- name: "Ensure base directory {{ postgresql_base_data_directory }}/ exists"
  ansible.builtin.file:
    path: "{{ postgresql_base_data_directory }}/"
    state: directory
  become: true

- name: "Ensure custom directory {{ postgresql_data_directory }}/ exists"
  ansible.builtin.file:
    path: "{{ postgresql_data_directory }}/"
    state: directory
  become: true

- name: PG | Configure PostgreSQL
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: "0640"

- name: PG | Copy PostgreSQL files to custom directory
  ansible.builtin.command:
    cmd: "rsync -av --exclude='*/' {{ postgresql_base_data_directory }}/ {{ postgresql_data_directory }}/"
  become: true

- name: PG | Allow PostgreSQL to listen on all interfaces
  ansible.builtin.lineinfile:
    path: "{{ postgresql_data_directory }}/postgresql.conf"
    regexp: "^#?listen_addresses = 'localhost'"
    line: "listen_addresses = '*'"
    state: present
  notify: Reload PostgreSQL

- name: PG | Ensure PostgreSQL service is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes