- name: PG | Create users
  become_user: postgres
  become: yes
  ansible.builtin.postgresql_user:
    state: present
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  loop: "{{ postgresql_create_users }}"
