- name: PG | Create databases
  become: yes
  become_user: postgres
  ansible.builtin.postgresql_db:
    name: "{{ item.name }}"
    login_user: postgres
  loop: "{{ postgresql_create_databases }}"
  #tags: molecule-idempotence-notest