- name: PG | Install PostgreSQL
  ansible.builtin.apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - python3-pip
      - libpq-dev
      - python3-dev
      - acl
      - sudo
      - rsync
    state: present
    update_cache: yes
  #tags: molecule-idempotence-notest

- name: PG | Install psycopg2 package
  ansible.builtin.pip:
    name: psycopg2
    state: present
  #tags: molecule-idempotence-notest
