- name: PG | Install PostgreSQL
  apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - python3-pip
      - libpq-dev
      - python3-dev
      - acl
      - sudo
      - rsync
    state: present
    update_cache: yes

#- name: PG | Install psycopg2 Python library
#  become: true
#  command: "/usr/bin/python3 -m pip install psycopg2"