- name: Enable replication in PostgreSQL configuration
  ansible.builtin.replace:
    path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp: '^(#?\s*){{ item.regex }}\s*=\s*.+$'
    replace: '\1{{ item.value }}'
    backup: yes
  loop:
    - { regex: 'wal_level', value: 'wal_level = replica' }
    - { regex: 'max_wal_senders', value: 'max_wal_senders = 10' }
    - { regex: 'wal_keep_segments', value: 'wal_keep_segments = 10' }

- name: Add replication user
  become_user: postgres
  ansible.builtin.postgresql_user:
    name: "{{ replication_username }}"
    password: "{{ replication_password }}"
    role_attr_flags: "REPLICATION"
  become: true
  notify: Restart PostgreSQL


- name: Allow replication connections in pg_hba.conf
  become_user: postgres
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    regexp: '^host\s+replication\s+{{ replication_username }}\s+'
    line: "host replication {{ replication_username }} all md5"
    state: present
  become: true
  notify: Restart PostgreSQL
