---
# handlers file for postgresql

- name: Reload PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: reloaded
    enabled: yes

- name: Restart PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes