---
# tasks file for prometheus
- name: Prometheus | install
  apt:
    name: prometheus
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Prometheus | args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus

- name: Prometheus | configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus

- name: Prometheus | start service
  service:
    name: prometheus
    state: started
    enabled: yes