---
# tasks file for openvpn
- name: OpenVPN | Install packages
  ansible.builtin.apt:
    name:
      - sudo
      - openvpn
      - easy-rsa
    update_cache: yes
    state: present
  notify:
    - enable openvpn

- name: OpenVPN | Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
    ignore_errors: true
  failed_when: false

- name: "OpenVPN | ensure {{ openvpn_dir }}/easyrsa exists"
  ansible.builtin.file:
    path: "{{ openvpn_dir }}/easy-rsa"
    state: directory
    mode: 0755

- name: "OpenVPN | ensure {{ openvpn_dir }}/server exists"
  ansible.builtin.file:
    path: "{{ openvpn_dir }}/server"
    state: directory
    mode: 0755

- name: OpenVPN | create vars file
  ansible.builtin.copy:
    dest: "{{ openvpn_easyrsa_dir }}/vars"
    content: |
      set_var EASYRSA_ALGO "ec"
      set_var EASYRSA_DIGEST "sha512"

- name: OpenVPN | Check if PKI directory exists
  ansible.builtin.stat:
    path: "{{ openvpn_dir }}/easy-rsa/pki"
  register: pki_dir

- name: OpenVPN | easy-rsa init-pki
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa init-pki"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki"
  when: not pki_dir.stat.exists

- name: OpenVPN | easy-rsa build-ca
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa build-ca nopass"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/ca.crt"
  environment:
    EASYRSA_BATCH: "yes"
  when: not pki_dir.stat.exists


- name: OpenVPN | easy-rsa gen-dh
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa gen-dh"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki/dh.pem"

- name: OpenVPN | easy-rsa server nopass
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa build-server-full server nopass"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki/issued/server.crt"

- name: OpenVPN | easy-rsa client nopass
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa build-client-full {{ item }} nopass"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki/issued/{{ item }}.crt"
  with_items:
    - "{{ openvpn_clients }}"


- name: OpenVPN | easy-rsa gen-crl
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa gen-crl"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki/crl.pem"

- name: OpenVPN | openvpn genkey
  ansible.builtin.command:
    cmd: "openvpn --genkey --secret {{ openvpn_dir }}/easy-rsa/pki/ta.key"
    creates: "{{ openvpn_dir }}/easy-rsa/pki/ta.key"

- name: "OpenVPN | copy files to {{ openvpn_dir }}/server"
  ansible.builtin.copy:
    src: "{{ openvpn_dir }}/easy-rsa/pki/{{ item }}"
    dest: "{{ openvpn_dir }}/server/{{ item | basename }}"
    mode: "0644"
    remote_src: true
  loop:
    - ca.crt
    - dh.pem
    - ta.key
    - private/ca.key
    - private/server.key
    - issued/server.crt

- name: "OpenVPN | copy files to {{ openvpn_dir }}"
  ansible.builtin.copy:
    src: "{{ openvpn_dir }}/easy-rsa/pki/{{ item }}"
    dest: "{{ openvpn_dir }}/{{ item | basename }}"
    mode: "0644"
    remote_src: true
  loop:
    - ca.crt
    - ta.key

- name: OpenVPN | place server.conf
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ openvpn_dir }}/server.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart openvpn