postgresql_data_directory: "/aboba/1234"
postgresql_version: "12"

postgresql_create_databases:
  - name: dbname1
  - name: dbname2
  - name: dbname3
postgresql_create_users:
  - name: user1
    password: secret1
  - name: user2
    password: secret2
  - name: user3
    password: secret3

replication_username: "replication_user"
replication_password: "your_replication_password"