---
# handlers file for openvpn
- name: restart openvpn
  ansible.builtin.service:
    name: openvpn
    state: restarted

- name: enable openvpn
  ansible.builtin.service:
    name: openvpn
    enabled: true
    state: started
