---
- name: app | Install Git
  ansible.builtin.apt:
    name: git
    state: present

- name: app | Clone django repo
  ansible.builtin.git:
    repo: 'https://github.com/mdn/django-locallibrary-tutorial'
    dest: "~/django/locallibrary"
    force: true

- name: app | Allow all hosts.ini.ini
  ansible.builtin.lineinfile:
    path: "~/django/locallibrary/locallibrary/settings.py"
    regexp: "ALLOWED_HOSTS"
    line: "ALLOWED_HOSTS = ['*']"

- name: app | Copy Dockerfile to target
  ansible.builtin.copy:
    src: "./Dockerfile"
    dest: "~/django/locallibrary//Dockerfile"

- name: app | Build Docker image
  community.general.docker_image:
    build:
      path: "~/django/locallibrary/"
    name: "django"
    source: build

- name: app | Apply migrations
  community.general.docker_container:
    name: "django_c"
    image: "django"
    command: python manage.py makemigrations
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    detach: false

- name: app | Apply database migrations
  community.general.docker_container:
    name: "django_c"
    image: "django"
    command: python manage.py migrate
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    detach: false

- name: app | Collect static files
  community.general.docker_container:
    name: "django_c"
    image: "django"
    command: python manage.py collectstatic --noinput
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    detach: false

- name: app | Run test suite
  community.general.docker_container:
    name: "django_c"
    image: "django"
    command: python manage.py test
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    detach: false

- name: app | Create Django superuser
  community.general.docker_container:
    name: "django_c"
    image: "django"

    command: "python manage.py createsuperuser --noinput --username=admin --email=admin@{{ inventory_hostname }}.com"
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    detach: false
  ignore_errors: true

- name: app | Run Docker container
  community.general.docker_container:
    name: "django_c"
    image: "django"
    state: started
    recreate: true
    published_ports:
      - "8000:8000"
    volumes:
      - "~/django/locallibrary/:/usr/src/app"
    command: python manage.py runserver 0.0.0.0:8000
