---
- name: Docker | pkg install
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    update-cache: true

- name: Docker | add docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Docker | add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64/v8] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Docker | Install Docker
  ansible.builtin.apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
    update-cache: true