---
# tasks file for app
- ansible.builtin.include_tasks: install.yml

- name: clone spring-boot-demo
  ansible.builtin.git:
    repo: "https://github.com/grafana/spring-boot-demo.git"
    dest: /usr/src/spring-boot-demo
    force: true
    update: yes

- name: build spring-boot-demo
  ansible.builtin.command:
    cmd: "./gradlew :bootRun"
  args:
    chdir: /usr/src/spring-boot-demo/
