Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"
  # Количество требуемых машин
  APPS = 1
  DBS = 1
  # Имя сетевого интерфейса для организации моста
  BRIDGE = "en0: Wi-Fi (Wireless)"

  def create_host(config, hostname, ip)
    config.vm.define hostname do |host|
      host.vm.network "private_network", ip: ip
      host.vm.network "public_network", bridge: BRIDGE
      host.vm.hostname = hostname
      host.vm.provision "shell", inline: "apt-get update && apt-get install -y python3-minimal"
      yield host if block_given?
    end
  end

  (1..APPS).each do |machine_id|
    create_host(config, "app#{machine_id}", "192.168.56.#{200+machine_id}")
  end

  (1..DBS).each do |machine_id|
      create_host(config, "db#{machine_id}", "192.168.56.#{200+APPS+machine_id}")
    end

end
