---
- name: Go | Download and extract Go archive
  ansible.builtin.get_url:
    url: "{{ go_download_url }}"
    dest: "{{ go_install_dir }}/go.tar.gz"
    mode: "0755"
    timeout: 180

- name: Go | Extract Go archive
  ansible.builtin.unarchive:
    src: "{{ go_install_dir }}/go.tar.gz"
    dest: "{{ go_install_dir }}"
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: Go | Set Go environment variables
  lineinfile:
    dest: /etc/profile.d/golang.sh
    line: "export PATH=$PATH:{{ go_install_path }}/bin"
    create: yes
