---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify | grafana is running
      ansible.builtin.uri:
          url: "http://{{ ansible_host }}:3000"
          status_code: 200
      register: response
      until: response.status == 200
      retries: 10
      delay: 5
