---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance2
    image: d3pre5s/ubuntu-py:20.04
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
