---
# tasks file for docker
- name: docker | install docker requirements
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    update-cache: true
    state: present

- name: docker | add docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: docker | add repository into sources list
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: docker | Install Docker
  apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: present
    update-cache: true