---
# handlers file for prometheus

- name: restart_prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes

- name: reload_prometheus
  uri:
    url: "http://{{ ansible_host }}:9090/-/reload"
    method: POST
    status_code: 200
